# Generated by Django 5.2.10 on 2026-01-26 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("applications_added", models.PositiveIntegerField(default=0)),
                ("applications_updated", models.PositiveIntegerField(default=0)),
                ("interviews_scheduled", models.PositiveIntegerField(default=0)),
                ("interviews_completed", models.PositiveIntegerField(default=0)),
                ("rejections_received", models.PositiveIntegerField(default=0)),
                ("offers_received", models.PositiveIntegerField(default=0)),
                ("follow_ups_sent", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyDigest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("total_applications", models.PositiveIntegerField(default=0)),
                ("new_applications", models.PositiveIntegerField(default=0)),
                ("interviews_scheduled", models.PositiveIntegerField(default=0)),
                ("interviews_completed", models.PositiveIntegerField(default=0)),
                ("rejections", models.PositiveIntegerField(default=0)),
                ("offers", models.PositiveIntegerField(default=0)),
                (
                    "response_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "interview_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "unique_together": {("user", "week_start")},
            },
        ),
    ]
