# Generated by Django 5.2.10 on 2026-01-26 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorshipRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mentor_name", models.CharField(max_length=200)),
                ("mentor_role", models.CharField(blank=True, max_length=200)),
                ("mentor_company", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("seeking", "Seeking Mentor"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="seeking",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("ad_hoc", "As Needed"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("goals", models.JSONField(blank=True, default=list)),
                ("focus_areas", models.JSONField(blank=True, default=list)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("next_session", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("agenda", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("action_items", models.JSONField(blank=True, default=list)),
                ("rating", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="networking.mentorshiprelationship",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("linkedin_url", models.URLField(blank=True)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("in_person", "In Person"),
                            ("conference", "Conference"),
                            ("referral", "Referral"),
                            ("alumni", "Alumni"),
                            ("other", "Other"),
                        ],
                        default="linkedin",
                        max_length=20,
                    ),
                ),
                (
                    "relationship_strength",
                    models.CharField(
                        choices=[
                            ("weak", "Weak (Met once)"),
                            ("moderate", "Moderate (Occasional contact)"),
                            ("strong", "Strong (Regular contact)"),
                            ("close", "Close (Trusted relationship)"),
                        ],
                        default="weak",
                        max_length=20,
                    ),
                ),
                ("met_at", models.CharField(blank=True, max_length=200)),
                ("met_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_alumni", models.BooleanField(default=False)),
                ("shared_school", models.CharField(blank=True, max_length=200)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("last_contact_date", models.DateField(blank=True, null=True)),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("meetup", "Meetup"),
                            ("career_fair", "Career Fair"),
                            ("webinar", "Webinar"),
                            ("coffee_chat", "Coffee Chat"),
                            ("informational", "Informational Interview"),
                            ("other", "Other"),
                        ],
                        default="meetup",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("virtual_link", models.URLField(blank=True)),
                ("is_virtual", models.BooleanField(default=False)),
                ("companies", models.JSONField(blank=True, default=list)),
                ("preparation_notes", models.TextField(blank=True)),
                ("post_event_notes", models.TextField(blank=True)),
                ("follow_up_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connections_made",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events_attended",
                        to="networking.professionalconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="mentorshiprelationship",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentorships",
                to="networking.professionalconnection",
            ),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("referrer_name", models.CharField(max_length=200)),
                ("referrer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("hired", "Hired (Success!)"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("referral_date", models.DateField(auto_now_add=True)),
                ("referral_code", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("thank_you_sent", models.BooleanField(default=False)),
                ("thank_you_date", models.DateField(blank=True, null=True)),
                ("referral_bonus_received", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_given",
                        to="networking.professionalconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="professionalconnection",
            index=models.Index(
                fields=["user", "company"], name="networking__user_id_de5445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalconnection",
            index=models.Index(
                fields=["user", "is_alumni"], name="networking__user_id_f3c485_idx"
            ),
        ),
    ]
