# Generated by Django 5.2.10 on 2026-01-26 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("category", models.CharField(max_length=100)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("behavioral", "Behavioral"),
                            ("technical", "Technical"),
                            ("situational", "Situational"),
                            ("competency", "Competency"),
                            ("brain_teaser", "Brain Teaser"),
                            ("case", "Case"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("roles", models.JSONField(blank=True, default=list)),
                ("tips", models.TextField(blank=True)),
                ("sample_answer", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "question_type"],
            },
        ),
        migrations.CreateModel(
            name="CompanyResearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mission_statement", models.TextField(blank=True)),
                ("values", models.JSONField(blank=True, default=list)),
                ("recent_news", models.TextField(blank=True)),
                ("products_services", models.TextField(blank=True)),
                ("competitors", models.JSONField(blank=True, default=list)),
                ("culture_notes", models.TextField(blank=True)),
                ("key_people", models.JSONField(blank=True, default=list)),
                ("questions_to_ask", models.JSONField(blank=True, default=list)),
                ("why_interested", models.TextField(blank=True)),
                ("how_you_fit", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_research",
                        to="applications.jobapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone_screen", "Phone Screen"),
                            ("video_call", "Video Call"),
                            ("onsite", "On-site"),
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("case_study", "Case Study"),
                            ("panel", "Panel"),
                            ("final", "Final Round"),
                            ("other", "Other"),
                        ],
                        default="video_call",
                        max_length=20,
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("meeting_link", models.URLField(blank=True)),
                ("meeting_id", models.CharField(blank=True, max_length=100)),
                ("meeting_password", models.CharField(blank=True, max_length=50)),
                ("interviewer_name", models.CharField(blank=True, max_length=200)),
                ("interviewer_title", models.CharField(blank=True, max_length=200)),
                ("interviewer_email", models.EmailField(blank=True, max_length=254)),
                ("interviewer_linkedin", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("preparation_notes", models.TextField(blank=True)),
                ("post_interview_notes", models.TextField(blank=True)),
                ("feedback", models.TextField(blank=True)),
                ("rating", models.PositiveIntegerField(blank=True, null=True)),
                ("google_event_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("behavioral", "Behavioral"),
                            ("technical", "Technical"),
                            ("situational", "Situational"),
                            ("competency", "Competency"),
                            ("brain_teaser", "Brain Teaser"),
                            ("case", "Case"),
                            ("other", "Other"),
                        ],
                        default="behavioral",
                        max_length=20,
                    ),
                ),
                ("is_common", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="interviews.interview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="STARResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "situation",
                    models.TextField(help_text="Describe the situation or context"),
                ),
                (
                    "task",
                    models.TextField(
                        help_text="Explain the task you needed to accomplish"
                    ),
                ),
                ("action", models.TextField(help_text="Describe the actions you took")),
                (
                    "result",
                    models.TextField(help_text="Share the results of your actions"),
                ),
                ("ai_suggestions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_responses",
                        to="interviews.interviewquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["application", "scheduled_at"],
                name="interviews__applica_aa1851_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["status", "scheduled_at"], name="interviews__status_39545c_idx"
            ),
        ),
    ]
