# Generated by Django 5.2.10 on 2026-01-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpTooltip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                (
                    "tooltip_type",
                    models.CharField(
                        choices=[
                            ("application_form", "Application Form"),
                            ("dashboard", "Dashboard"),
                            ("analytics", "Analytics"),
                            ("reminders", "Reminders"),
                            ("settings", "Settings"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("placement", models.CharField(default="top", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("show_to_new_users", models.BooleanField(default=True)),
                ("show_after_days", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SampleDataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("applications_created", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_data_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorialProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tutorial_type",
                    models.CharField(
                        choices=[
                            ("application_tracking", "Application Tracking"),
                            ("analytics_dashboard", "Analytics Dashboard"),
                            ("calendar_integration", "Calendar Integration"),
                            ("reminders_system", "Reminders System"),
                        ],
                        max_length=30,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=1)),
                ("completed_steps", models.JSONField(default=list)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tutorial_type")},
            },
        ),
    ]
