# Generated by Django 5.2.10 on 2026-01-26 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("target_role", models.CharField(max_length=200)),
                ("target_level", models.CharField(blank=True, max_length=50)),
                ("estimated_weeks", models.PositiveIntegerField(default=12)),
                ("total_hours", models.PositiveIntegerField(default=0)),
                ("followers_count", models.PositiveIntegerField(default=0)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-followers_count"],
            },
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("course", "Online Course"),
                            ("book", "Book"),
                            ("tutorial", "Tutorial"),
                            ("certification", "Certification"),
                            ("bootcamp", "Bootcamp"),
                            ("workshop", "Workshop"),
                            ("project", "Practice Project"),
                            ("other", "Other"),
                        ],
                        default="course",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("coursera", "Coursera"),
                            ("udemy", "Udemy"),
                            ("linkedin", "LinkedIn Learning"),
                            ("pluralsight", "Pluralsight"),
                            ("udacity", "Udacity"),
                            ("edx", "edX"),
                            ("youtube", "YouTube"),
                            ("freecodecamp", "freeCodeCamp"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("difficulty_level", models.CharField(blank=True, max_length=20)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("is_ai_recommended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating", "-reviews_count"],
            },
        ),
        migrations.CreateModel(
            name="CareerGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("role", "Target Role"),
                            ("salary", "Salary Target"),
                            ("skill", "Skill Acquisition"),
                            ("certification", "Certification"),
                            ("company", "Target Company"),
                            ("industry", "Industry Change"),
                            ("custom", "Custom Goal"),
                        ],
                        default="role",
                        max_length=20,
                    ),
                ),
                (
                    "time_frame",
                    models.CharField(
                        choices=[
                            ("short", "Short Term (0-6 months)"),
                            ("medium", "Medium Term (6-18 months)"),
                            ("long", "Long Term (18+ months)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("achieved", "Achieved"),
                            ("deferred", "Deferred"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("target_value", models.CharField(blank=True, max_length=200)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                ("milestones", models.JSONField(default=list)),
                ("ai_recommendations", models.JSONField(default=list)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareerPathPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("current_role", models.CharField(max_length=200)),
                ("current_level", models.CharField(blank=True, max_length=50)),
                (
                    "current_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("target_role", models.CharField(max_length=200)),
                ("target_level", models.CharField(blank=True, max_length=50)),
                (
                    "target_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("target_timeline_years", models.PositiveIntegerField(default=5)),
                ("stages", models.JSONField(default=list)),
                ("ai_analysis", models.TextField(blank=True)),
                (
                    "success_probability",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("market_demand", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPathResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career.learningpath",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career.learningresource",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("learning_path", "resource")},
            },
        ),
        migrations.AddField(
            model_name="learningpath",
            name="resources",
            field=models.ManyToManyField(
                related_name="learning_paths",
                through="career.LearningPathResource",
                to="career.learningresource",
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("normalized_name", models.CharField(db_index=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("soft", "Soft Skills"),
                            ("language", "Language"),
                            ("tools", "Tools & Software"),
                            ("framework", "Framework"),
                            ("certification", "Certification"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_skills",
                    models.ManyToManyField(blank=True, to="career.skill"),
                ),
            ],
            options={
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("mobile", "Mobile App"),
                            ("api", "API/Backend"),
                            ("data", "Data Science"),
                            ("ml", "Machine Learning"),
                            ("design", "Design"),
                            ("writing", "Writing/Content"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("demo_video_url", models.URLField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/thumbnails/"
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                ("technologies", models.JSONField(default=list)),
                ("challenges", models.TextField(blank=True)),
                ("outcomes", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills_demonstrated",
                    models.ManyToManyField(
                        blank=True, related_name="portfolio_projects", to="career.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="learningresource",
            name="skills",
            field=models.ManyToManyField(
                related_name="learning_resources", to="career.skill"
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="skills",
            field=models.ManyToManyField(
                related_name="learning_paths", to="career.skill"
            ),
        ),
        migrations.CreateModel(
            name="SkillGapAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_role", models.CharField(max_length=200)),
                ("target_company", models.CharField(blank=True, max_length=200)),
                ("target_industry", models.CharField(blank=True, max_length=100)),
                ("required_skills", models.JSONField(default=list)),
                ("current_skills", models.JSONField(default=list)),
                ("gap_skills", models.JSONField(default=list)),
                (
                    "match_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("summary", models.TextField(blank=True)),
                ("recommendations", models.JSONField(default=list)),
                (
                    "estimated_time_to_bridge",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_analyses",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_gap_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLearningPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_users",
                        to="career.learningpath",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "unique_together": {("user", "learning_path")},
            },
        ),
        migrations.CreateModel(
            name="UserLearningProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_time_spent_minutes", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("user_rating", models.PositiveIntegerField(blank=True, null=True)),
                ("user_review", models.TextField(blank=True)),
                ("certificate_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="career.learningresource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "resource")},
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("last_used", models.DateField(blank=True, null=True)),
                ("ai_assessed_level", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="career.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-proficiency", "-years_of_experience"],
                "unique_together": {("user", "skill")},
            },
        ),
    ]
