# Generated by Django 5.2.10 on 2026-01-26 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryTrend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("industry", models.CharField(db_index=True, max_length=100)),
                ("sub_industry", models.CharField(blank=True, max_length=100)),
                ("hiring_trend", models.CharField(max_length=50)),
                (
                    "growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("open_positions", models.PositiveIntegerField(default=0)),
                (
                    "average_time_to_fill",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("competition_level", models.CharField(blank=True, max_length=50)),
                (
                    "average_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("top_skills", models.JSONField(default=list)),
                ("emerging_skills", models.JSONField(default=list)),
                ("declining_skills", models.JSONField(default=list)),
                ("top_hiring_companies", models.JSONField(default=list)),
                ("top_locations", models.JSONField(default=list)),
                (
                    "remote_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_predictions", models.JSONField(default=list)),
                ("year", models.PositiveIntegerField()),
                ("quarter", models.PositiveIntegerField(blank=True, null=True)),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "-quarter"],
            },
        ),
        migrations.CreateModel(
            name="JobMarketHeatmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("job_category", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("job_count", models.PositiveIntegerField(default=0)),
                ("companies_count", models.PositiveIntegerField(default=0)),
                (
                    "average_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost_of_living_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "adjusted_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "job_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-job_count"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("domain", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("sub_industry", models.CharField(blank=True, max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("startup", "Startup (1-50)"),
                            ("small", "Small (51-200)"),
                            ("medium", "Medium (201-1000)"),
                            ("large", "Large (1001-5000)"),
                            ("enterprise", "Enterprise (5000+)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=200)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(default=False)),
                ("stock_symbol", models.CharField(blank=True, max_length=20)),
                ("estimated_revenue", models.CharField(blank=True, max_length=100)),
                ("funding_stage", models.CharField(blank=True, max_length=50)),
                ("total_funding", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("glassdoor_url", models.URLField(blank=True)),
                ("careers_page", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                (
                    "glassdoor_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "employee_satisfaction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("culture_keywords", models.JSONField(blank=True, default=list)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("is_hiring", models.BooleanField(default=True)),
                ("open_positions_count", models.PositiveIntegerField(default=0)),
                ("hiring_velocity", models.CharField(blank=True, max_length=50)),
                (
                    "interview_difficulty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "typical_interview_rounds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("interview_process", models.JSONField(blank=True, default=list)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_pros", models.JSONField(blank=True, default=list)),
                ("ai_cons", models.JSONField(blank=True, default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["industry"], name="market_inte_industr_0ed014_idx"
                    ),
                    models.Index(
                        fields=["company_size"], name="market_inte_company_7d0336_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HiringSeasonData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("industry", models.CharField(db_index=True, max_length=100)),
                ("job_category", models.CharField(blank=True, max_length=100)),
                (
                    "january_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "february_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "march_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "april_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "may_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "june_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "july_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "august_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "september_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "october_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "november_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "december_index",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                ("peak_months", models.JSONField(default=list)),
                ("slow_months", models.JSONField(default=list)),
                ("best_time_to_apply", models.TextField(blank=True)),
                ("year", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("industry", "job_category", "year")},
            },
        ),
        migrations.CreateModel(
            name="JobSearchROI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_applications", models.PositiveIntegerField(default=0)),
                (
                    "total_hours_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("resume_versions_created", models.PositiveIntegerField(default=0)),
                ("networking_events_attended", models.PositiveIntegerField(default=0)),
                ("courses_completed", models.PositiveIntegerField(default=0)),
                ("responses_received", models.PositiveIntegerField(default=0)),
                ("interviews_scheduled", models.PositiveIntegerField(default=0)),
                ("interviews_completed", models.PositiveIntegerField(default=0)),
                ("offers_received", models.PositiveIntegerField(default=0)),
                (
                    "response_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "interview_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "offer_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "initial_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "final_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_increase",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estimated_job_search_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "efficiency_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("recommendations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_search_roi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="SuccessPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "skill_match_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "experience_match_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "company_fit_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "resume_quality_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "response_probability",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "interview_probability",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "offer_probability",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("similar_applications_count", models.PositiveIntegerField(default=0)),
                (
                    "similar_success_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("model_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="SalaryData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(db_index=True, max_length=200)),
                ("normalized_title", models.CharField(db_index=True, max_length=200)),
                ("seniority_level", models.CharField(blank=True, max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("is_remote", models.BooleanField(default=False)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("salary_min", models.DecimalField(decimal_places=2, max_digits=12)),
                ("salary_max", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "salary_median",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bonus_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bonus_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "equity_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "equity_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_comp_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_comp_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("sample_size", models.PositiveIntegerField(default=1)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("quarter", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_data",
                        to="market_intel.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-salary_median"],
                "indexes": [
                    models.Index(
                        fields=["normalized_title", "location"],
                        name="market_inte_normali_9d16c1_idx",
                    ),
                    models.Index(
                        fields=["industry", "year"],
                        name="market_inte_industr_78fbbd_idx",
                    ),
                ],
            },
        ),
    ]
