# Generated by Django 5.2.10 on 2026-01-26 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV"), ("pdf", "PDF")],
                        default="json",
                        max_length=10,
                    ),
                ),
                ("include_applications", models.BooleanField(default=True)),
                ("include_interviews", models.BooleanField(default=True)),
                ("include_contacts", models.BooleanField(default=True)),
                ("include_notes", models.BooleanField(default=True)),
                ("include_analytics", models.BooleanField(default=True)),
                ("include_ai_data", models.BooleanField(default=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("download_url", models.URLField(blank=True)),
                ("download_token", models.CharField(blank=True, max_length=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EncryptedNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("encrypted_content", models.TextField()),
                ("category", models.CharField(blank=True, max_length=50)),
                ("tags", models.JSONField(default=list)),
                ("encryption_version", models.CharField(default="v1", max_length=20)),
                ("iv", models.CharField(blank=True, max_length=100)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_notes",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GDPRRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("export", "Data Export (Art. 15)"),
                            ("deletion", "Data Deletion (Art. 17)"),
                            ("rectification", "Data Rectification (Art. 16)"),
                            ("portability", "Data Portability (Art. 20)"),
                            ("restriction", "Processing Restriction (Art. 18)"),
                            ("objection", "Objection to Processing (Art. 21)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("verification_pending", "Verification Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("data_to_correct", models.JSONField(blank=True, default=dict)),
                ("verification_code", models.CharField(blank=True, max_length=100)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verified_by", models.CharField(blank=True, max_length=100)),
                ("admin_notes", models.TextField(blank=True)),
                ("denial_reason", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_gdpr_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gdpr_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GDPR Request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacySetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allow_analytics", models.BooleanField(default=True)),
                ("allow_ai_training", models.BooleanField(default=False)),
                ("allow_personalization", models.BooleanField(default=True)),
                ("allow_marketing_emails", models.BooleanField(default=False)),
                ("allow_product_updates", models.BooleanField(default=True)),
                ("allow_tips_emails", models.BooleanField(default=True)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("connections", "Connections Only"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("show_in_leaderboards", models.BooleanField(default=True)),
                ("allow_anonymous_posts", models.BooleanField(default=True)),
                ("session_timeout_minutes", models.PositiveIntegerField(default=1440)),
                ("logout_on_inactivity", models.BooleanField(default=False)),
                (
                    "auto_delete_rejected_after_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Setting",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "primary_method",
                    models.CharField(
                        choices=[
                            ("totp", "Authenticator App (TOTP)"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("backup", "Backup Codes"),
                        ],
                        default="totp",
                        max_length=20,
                    ),
                ),
                ("totp_secret", models.CharField(blank=True, max_length=100)),
                ("totp_confirmed", models.BooleanField(default=False)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("phone_confirmed", models.BooleanField(default=False)),
                ("backup_codes_encrypted", models.TextField(blank=True)),
                ("backup_codes_used", models.JSONField(default=list)),
                ("recovery_email", models.EmailField(blank=True, max_length=254)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("trusted_devices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Two-Factor Authentication",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("successful", models.BooleanField()),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("suspicious_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="privacy_log_email_c59ef6_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="privacy_log_ip_addr_04d25e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("email_change", "Email Change"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("2fa_disabled", "2FA Disabled"),
                            ("data_export", "Data Export"),
                            ("data_deletion", "Data Deletion"),
                            ("permission_change", "Permission Change"),
                            ("api_key_created", "API Key Created"),
                            ("api_key_revoked", "API Key Revoked"),
                            ("suspicious", "Suspicious Activity"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("severity", models.CharField(default="info", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Audit Log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="privacy_sec_user_id_cc0608_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="privacy_sec_created_f14d39_idx"
                    ),
                ],
            },
        ),
    ]
